workflows:
  android-workflow:
    name: Android Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "io.github.uditkarode.able"
    scripts:
      - name: Check directory structure
        script: |
          echo "Root directory: $(pwd)"
          ls -la
      - name: Navigate to project directory
        script: |
          cd AbleMusicPlayer-master
          echo "Project directory: $(pwd)"
          ls -la
      - name: Set up local properties
        script: |
          cd AbleMusicPlayer-master
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
      - name: Update dependency settings
        script: |
          cd AbleMusicPlayer-master
          echo "Original settings.gradle.kts content:"
          cat settings.gradle.kts
          
          # Backup original settings file
          cp settings.gradle.kts settings.gradle.kts.bak
          
          # Update settings.gradle.kts to use an authentication token with JitPack
          sed -i '' 's|maven(url = "https://jitpack.io")|maven { url = uri("https://jitpack.io"); credentials { username = "jp_123456789" } }|g' settings.gradle.kts
          
          echo "Updated settings.gradle.kts content:"
          cat settings.gradle.kts
          
          # Update version of NewPipeExtractor if needed
          find . -name "*.gradle" -o -name "*.gradle.kts" | xargs grep -l "NewPipeExtractor" | xargs cat
      - name: Try direct download of dependency
        script: |
          cd AbleMusicPlayer-master
          mkdir -p libs
          curl -L "https://jitpack.io/com/github/TeamNewPipe/NewPipeExtractor/v0.24.2/NewPipeExtractor-v0.24.2.jar" -o libs/NewPipeExtractor-v0.24.2.jar || echo "Failed to download jar directly"
          # Create local.properties with custom maven local
          echo "maven.local=./libs" >> local.properties
      - name: Build with specific configuration
        script: |
          cd AbleMusicPlayer-master
          chmod +x ./gradlew
          # Try to build with specific flags to handle dependency issues
          ./gradlew assembleDebug --stacktrace --refresh-dependencies --no-configuration-cache
    artifacts:
      - AbleMusicPlayer-master/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - myntrasinghania@gmail.com 