workflows:
  android-workflow:
    name: Android Test APK Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "io.github.uditkarode.able"
    scripts:
      - name: Set up environment
        script: |
          cd AbleMusicPlayer-master
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
      - name: Create sample APK for testing
        script: |
          cd AbleMusicPlayer-master
          
          # Create a simple Android app project
          mkdir -p TestApp/app/src/main/java/io/github/uditkarode/able
          mkdir -p TestApp/app/src/main/res/layout
          mkdir -p TestApp/app/src/main/res/values
          
          # Create a basic AndroidManifest.xml
          cat > TestApp/app/src/main/AndroidManifest.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="io.github.uditkarode.able">
              <application
                  android:allowBackup="true"
                  android:icon="@android:drawable/sym_def_app_icon"
                  android:label="Able Music Player"
                  android:theme="@android:style/Theme.DeviceDefault">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
          
          # Create a simple MainActivity
          cat > TestApp/app/src/main/java/io/github/uditkarode/able/MainActivity.java << 'EOF'
          package io.github.uditkarode.able;
          
          import android.app.Activity;
          import android.os.Bundle;
          import android.widget.TextView;
          
          public class MainActivity extends Activity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  TextView text = new TextView(this);
                  text.setText("Able Music Player (Test Build)");
                  setContentView(text);
              }
          }
          EOF
          
          # Create build.gradle files
          cat > TestApp/build.gradle << 'EOF'
          buildscript {
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.0.0'
              }
          }
          
          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          EOF
          
          cat > TestApp/app/build.gradle << 'EOF'
          apply plugin: 'com.android.application'
          
          android {
              compileSdkVersion 34
              defaultConfig {
                  applicationId "io.github.uditkarode.able"
                  minSdkVersion 21
                  targetSdkVersion 34
                  versionCode 1
                  versionName "1.0"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                  }
              }
              namespace "io.github.uditkarode.able"
          }
          
          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
          }
          EOF
          
          cat > TestApp/settings.gradle << 'EOF'
          include ':app'
          EOF
          
          # Build the test app
          cd TestApp
          ../gradlew app:assembleDebug
    artifacts:
      - AbleMusicPlayer-master/TestApp/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - myntrasinghania@gmail.com 