workflows:
  android-workflow:
    name: Android Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "io.github.uditkarode.able"
    scripts:
      - name: Check directory structure
        script: |
          echo "Root directory: $(pwd)"
          ls -la
      - name: Navigate to project directory
        script: |
          cd AbleMusicPlayer-master
          echo "Project directory: $(pwd)"
          ls -la
      - name: Set up local properties
        script: |
          cd AbleMusicPlayer-master
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
      - name: Modify settings to exclude problematic modules
        script: |
          cd AbleMusicPlayer-master
          
          # Backup original settings.gradle.kts
          cp settings.gradle.kts settings.gradle.kts.bak
          
          # Show original settings
          echo "Original settings.gradle.kts:"
          cat settings.gradle.kts
          
          # Create a simpler version of settings.gradle.kts for CI build
          # Keep only the app module and minimal required settings
          cat > settings.gradle.kts << 'EOF'
          @file:Suppress("UnstableApiUsage")
          
          enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
          
          pluginManagement {
              includeBuild("build-logic")
              repositories {
                  google()
                  mavenCentral()
                  gradlePluginPortal()
                  maven(url = "https://plugins.gradle.org/m2/")
                  maven(url = "https://jitpack.io")
              }
          }
          
          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
                  maven(url = "https://jitpack.io")
                  maven(url = "https://plugins.gradle.org/m2/")
              }
          }
          
          rootProject.name = "YoutubeMobile"
          include(":app")
          EOF
          
          echo "Modified settings.gradle.kts:"
          cat settings.gradle.kts
      - name: Create minimal app module for test build
        script: |
          cd AbleMusicPlayer-master
          
          # Create a backup of app's build.gradle.kts
          APP_BUILD_FILE=$(find app -name "build.gradle.kts")
          if [ -n "$APP_BUILD_FILE" ]; then
            cp "$APP_BUILD_FILE" "${APP_BUILD_FILE}.bak"
            echo "Original app build.gradle.kts:"
            cat "$APP_BUILD_FILE"
            
            # Modify the app's build.gradle.kts to remove dependencies on core modules
            sed -i.bak 's/implementation(projects.core.*/\/\/ Temporarily commented for CI build: &/' "$APP_BUILD_FILE"
            
            echo "Modified app build.gradle.kts:"
            cat "$APP_BUILD_FILE"
          fi
      - name: Build simplified app module
        script: |
          cd AbleMusicPlayer-master
          chmod +x ./gradlew
          
          # Try to build only the app module with basic functionality
          ./gradlew :app:assembleDebug -x lint --info
    artifacts:
      - AbleMusicPlayer-master/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - myntrasinghania@gmail.com 