workflows:
  android-workflow:
    name: Android Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "io.github.uditkarode.able"
    scripts:
      - name: Check directory structure
        script: |
          echo "Root directory: $(pwd)"
          ls -la
      - name: Navigate to project directory
        script: |
          cd AbleMusicPlayer-master
          echo "Project directory: $(pwd)"
          ls -la
      - name: Set up local properties
        script: |
          cd AbleMusicPlayer-master
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
      - name: Inspect and enhance Gradle settings
        script: |
          cd AbleMusicPlayer-master
          echo "Original settings.gradle.kts content:"
          cat settings.gradle.kts
          
          # Create gradle.properties with JitPack authentication workaround
          echo "Adding GitHub authentication workaround to gradle.properties"
          echo "# Added for CI build to avoid JitPack rate limiting" >> gradle.properties
          echo "authToken=jp_123456789" >> gradle.properties
          
          # Create or modify init.gradle for global JitPack configuration
          mkdir -p ~/.gradle
          cat > ~/.gradle/init.gradle << EOF
          allprojects {
              repositories {
                  maven {
                      url "https://jitpack.io"
                      credentials { username authToken }
                  }
              }
          }
          EOF
          
          echo "Updated gradle.properties content:"
          cat gradle.properties
      - name: Show project dependencies
        script: |
          cd AbleMusicPlayer-master
          chmod +x ./gradlew
          ./gradlew :core:services:dependencies --configuration debugCompileClasspath | grep -A 5 NewPipeExtractor
      - name: Attempt build with offline mode
        script: |
          cd AbleMusicPlayer-master
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace --refresh-dependencies
    artifacts:
      - AbleMusicPlayer-master/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - myntrasinghania@gmail.com 