workflows:
  android-workflow:
    name: Android Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "io.github.uditkarode.able"
    scripts:
      - name: Check directory structure
        script: |
          echo "Root directory: $(pwd)"
          ls -la
      - name: Navigate to project directory
        script: |
          cd AbleMusicPlayer-master
          echo "Project directory: $(pwd)"
          ls -la
      - name: Set up local properties
        script: |
          cd AbleMusicPlayer-master
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
      - name: Build debug APK
        script: |
          cd AbleMusicPlayer-master
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - AbleMusicPlayer-master/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - myntrasinghania@gmail.com 